import"./assets/header-chenges-theme-57b0d9e4.js";import{a as u,i as h,b as y,g as f}from"./assets/vendor-85b191d9.js";const s={MAIN_URl:"https://books-backend.p.goit.global/books/",CATEGORY_LIST_URL:"https://books-backend.p.goit.global/books/category-list",POPULAR_BOOKS_ALL_CATEGORIES:"https://books-backend.p.goit.global/books/top-books",SELECTED_CATEGORY:"https://books-backend.p.goit.global/books/category"};async function c(t,e){return await u.get(t,{params:{category:e}})}function d(){return h.show({message:"We were not able to fetch your data. Try again!",messageColor:"white",backgroundColor:"#EF4040",position:"topRight"})}const r=document.querySelector(".main-page-books-section");document.querySelector(".best-sellers-books-section");const S=document.querySelector(".best-sellers-header"),E=document.querySelector(".categories");let l=null;async function g(){return await c(s.POPULAR_BOOKS_ALL_CATEGORIES).then(({data:t})=>{if(t.length)return S.innerHTML="Best Sellers <span>Books</span>",r.innerHTML=C(t),l=document.querySelectorAll(".book-shelf-container"),l.forEach((e,o)=>{const n=t[o];return e.innerHTML=_([n]),t}),B(),terSeeMoreBtn(),t;d()}).catch(t=>console.log(t))}function C(t){return t.map(e=>`<div class="book-shelf">
      <p class="book-shelf-category">${e.list_name}</p>
      <div class="book-shelf-container"></div>
      <button class="see-more-btn" type="button" data-category="${e.list_name}">SEE MORE</button>
    </div>`).join("")}function B(){return r.addEventListener("click",t=>{t.target.nodeName==="BUTTON"&&t.target.hasAttribute("data-category")&&c(s.SELECTED_CATEGORY,t.target.getAttribute("data-category")).then(({data:e})=>{e.length?(t.stopPropagation(),r.innerHTML="",r.classList.add("book-grid"),r.innerHTML=p(e)):d()}).catch(e=>console.error(e))})}function L(){return E.addEventListener("click",t=>{t.target.nodeName==="BUTTON"&&t.target.hasAttribute("data-id")?c(s.SELECTED_CATEGORY,t.target.getAttribute("data-id")).then(({data:e})=>{t.stopPropagation(),r.innerHTML="",r.classList.add("book-grid"),r.innerHTML=p(e)}).catch(e=>console.error(e)):t.target.nodeName==="BUTTON"&&t.target.hasAttribute("name")&&g()})}function _(t){return t.map((e,o)=>e.books.map((n,a)=>{let i;window.innerWidth<768?i=1:window.innerWidth<1440?i=3:i=5;const b=window.innerWidth<768&&a===0,k=a<i;return`<div class="book-card-container${b?" marked":""}" style="display: ${k?"block":"none"};"><a class="book-item-link" href="#" data-bookid="${n._id}">
            <img class="book-card-img" src="${n.book_image}" alt="" />
            <h2 class="book-card-title">${n.title}</h2>
            <p class="book-card-author">${n.author}</p>
              </div>`}).join(""))}function p(t){const e=document.querySelector(".best-sellers-header");console.log(t),e.textContent=t[0].list_name;const o=e.textContent.split(" "),n=o.pop();return e.innerHTML=o.join(" ")+' <span style="color: #4f2ee8;">'+n+"</span>",t.map(a=>`<div class="book-card-container" ><a class="book-item-link" href="#" data-bookid="${a._id}">
            <img class="book-card-img" src="${a.book_image}" alt="" />
            <h2 class="book-card-title">${a.title}</h2>
            <p class="book-card-author">${a.author}</p></div>`).join("")}g();const T={apiKey:"AIzaSyA3hADlXiNs1sXdUxR8pbsxRLOErTEmqfU",authDomain:"authorisation-3967f.firebaseapp.com",projectId:"authorisation-3967f",storageBucket:"authorisation-3967f.appspot.com",messagingSenderId:"926560198246",appId:"1:926560198246:web:e18f20ad2d2adfa37e97a7"},A=y(T);f(A);function m(){return{supportUkraineCnt:document.querySelector(".support-list"),divEl:document.querySelector(".shopping__list"),paginationsSection:document.querySelector(".paginations"),paginationContainerPages:document.querySelector(".paginations__container-pages"),paginationContainerBackBtn:document.querySelector(".paginations__container-back"),paginationContainerEndBtn:document.querySelector(".paginations__container-end"),startButton:document.querySelector("button[name='startButton']"),previousButton:document.querySelector("button[name='previousButton']"),nextButton:document.querySelector("button[name='nextButton']"),endButton:document.querySelector("button[name='endButton']"),activButton:document.querySelector(".active"),allCategoriesBtn:document.querySelector("button[name=allcategories]"),categoryListEl:document.querySelector(".categories_list"),categoriesListContainer:document.querySelector(".categories"),categoryContainerEl:document.querySelector(".content-rendering-container")}}const{categoriesListContainer:v}=m();v.addEventListener("click",q);function q(t){if(t.preventDefault(),t.target.nodeName!=="BUTTON")return;const e=t.target,o=document.querySelector(".active-category");o&&o!==e&&o.classList.remove("active-category"),e.classList.add("active-category")}const{categoryListEl:O}=m();async function w(){try{const{data:t}=await u.get("https://books-backend.p.goit.global/books/category-list");return t}catch(t){console.log(t)}}async function R(){try{const e=(await w()).sort((o,n)=>o.list_name.localeCompare(n.list_name));for(const o of e){const n=document.createElement("li"),a=document.createElement("button");a.setAttribute("type","button"),a.classList.add("category-btn"),a.textContent=`${o.list_name}`,a.setAttribute("data-id",o.list_name),O.appendChild(n),n.appendChild(a)}}catch(t){console.log(t)}}R();L();
//# sourceMappingURL=commonHelpers.js.map
