import{a as c,i as l,g as u,c as p}from"./assets/vendor-9b1e7844.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const d={MAIN_URl:"https://books-backend.p.goit.global/books/",CATEGORY_LIST_URL:"https://books-backend.p.goit.global/books/category-list",POPULAR_BOOKS_ALL_CATEGORIES:"https://books-backend.p.goit.global/books/top-books",SELECTED_CATEGORY:"https://books-backend.p.goit.global/books/category"};async function f(o,t){return await c.get(o,{params:{category:t}})}const g=document.querySelector(".main-page-books-section");let i=null;async function m(){return await f(d.POPULAR_BOOKS_ALL_CATEGORIES).then(({data:o})=>{g.innerHTML=b(o),i=document.querySelectorAll(".book-shelf-container"),i.forEach((t,r)=>{const n=o[r];t.innerHTML=h([n])})}).catch(o=>console.log(o))}function b(o){return o.map(t=>`<div class="book-shelf">
      <p class="book-shelf-category">${t.list_name}</p>
      <div class="book-shelf-container"></div>
    </div>`).join("")}function h(o){return o.map(t=>t.books.map(r=>`<div class="book-card-container">
  <img class="book-card-img" src="${r.book_image}" alt="" />
  <h2 class="book-card-title">${r.title}</h2>
  <p class="book-card-author">${r.author}</p>
</div>`).join(""))}m();const y={apiKey:"AIzaSyA3hADlXiNs1sXdUxR8pbsxRLOErTEmqfU",authDomain:"authorisation-3967f.firebaseapp.com",projectId:"authorisation-3967f",storageBucket:"authorisation-3967f.appspot.com",messagingSenderId:"926560198246",appId:"1:926560198246:web:e18f20ad2d2adfa37e97a7"},k=l(y),S=u(k),A=document.querySelector("#signup-form");A.addEventListener("submit",E);function E(o){o.preventDefault();const t=document.getElementById("signup-name").value,r=document.getElementById("signup-email").value;document.getElementById("signup-password").value,p(S,t,r).then(n=>{const e=n.user;console.log("Signed up:",e)}).catch(n=>{n.code;const e=n.message;console.error("Sign up error:",e)})}
//# sourceMappingURL=commonHelpers.js.map
